TRASH_LABELS = ["plastic", "metal", "paper", "glass", "organic", "generic"]

# COCO labels for yolov6-nano-r2-coco in the model's output order.
COCO_LABELS = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

# Unmapped labels remain None to avoid forcing a trash category.
COCO_TO_TRASH = {label: None for label in COCO_LABELS}
COCO_TO_TRASH.update(
    {
        "bottle": "plastic",
        "cup": "plastic",
        "toothbrush": "plastic",
        "remote": "plastic",
        "keyboard": "plastic",
        "mouse": "plastic",
        "cell phone": "plastic",
        "tv": "plastic",
        "laptop": "plastic",
        "fork": "metal",
        "knife": "metal",
        "spoon": "metal",
        "scissors": "metal",
        "book": "paper",
        "wine glass": "glass",
        "banana": "organic",
        "apple": "organic",
        "sandwich": "organic",
        "orange": "organic",
        "broccoli": "organic",
        "carrot": "organic",
        "hot dog": "organic",
        "pizza": "organic",
        "donut": "organic",
        "cake": "organic",
    }
)
